from z3 import *

def to_real(x):
    if isinstance(x, int):
        return RealVal(x)
    return ToReal(x)

s_p_0 = Int('s_p_0')
s_OUT_value_0 = Real('s_OUT_value_0')
s_OUT_reqRead_0 = Bool('s_OUT_reqRead_0')
s_OUT_reqWrite_0 = Bool('s_OUT_reqWrite_0')
m_IN_value_0 = Real('m_IN_value_0')
m_IN_reqRead_0 = Bool('m_IN_reqRead_0')
m_IN_reqWrite_0 = Bool('m_IN_reqWrite_0')
_smoother_0_count_0 = Int('_smoother_0_count_0')
_smoother_0_avg_0 = Int('_smoother_0_avg_0')

s_p_1 = Int('s_p_1')
s_OUT_value_1 = Real('s_OUT_value_1')
s_OUT_reqRead_1 = Bool('s_OUT_reqRead_1')
s_OUT_reqWrite_1 = Bool('s_OUT_reqWrite_1')
m_IN_value_1 = Real('m_IN_value_1')
m_IN_reqRead_1 = Bool('m_IN_reqRead_1')
m_IN_reqWrite_1 = Bool('m_IN_reqWrite_1')
_smoother_0_count_1 = Int('_smoother_0_count_1')
_smoother_0_avg_1 = Int('_smoother_0_avg_1')

s_p_2 = Int('s_p_2')
s_OUT_value_2 = Real('s_OUT_value_2')
s_OUT_reqRead_2 = Bool('s_OUT_reqRead_2')
s_OUT_reqWrite_2 = Bool('s_OUT_reqWrite_2')
m_IN_value_2 = Real('m_IN_value_2')
m_IN_reqRead_2 = Bool('m_IN_reqRead_2')
m_IN_reqWrite_2 = Bool('m_IN_reqWrite_2')
_smoother_0_count_2 = Int('_smoother_0_count_2')
_smoother_0_avg_2 = Int('_smoother_0_avg_2')

s_p_3 = Int('s_p_3')
s_OUT_value_3 = Real('s_OUT_value_3')
s_OUT_reqRead_3 = Bool('s_OUT_reqRead_3')
s_OUT_reqWrite_3 = Bool('s_OUT_reqWrite_3')
m_IN_value_3 = Real('m_IN_value_3')
m_IN_reqRead_3 = Bool('m_IN_reqRead_3')
m_IN_reqWrite_3 = Bool('m_IN_reqWrite_3')
_smoother_0_count_3 = Int('_smoother_0_count_3')
_smoother_0_avg_3 = Int('_smoother_0_avg_3')

s_p_4 = Int('s_p_4')
s_OUT_value_4 = Real('s_OUT_value_4')
s_OUT_reqRead_4 = Bool('s_OUT_reqRead_4')
s_OUT_reqWrite_4 = Bool('s_OUT_reqWrite_4')
m_IN_value_4 = Real('m_IN_value_4')
m_IN_reqRead_4 = Bool('m_IN_reqRead_4')
m_IN_reqWrite_4 = Bool('m_IN_reqWrite_4')
_smoother_0_count_4 = Int('_smoother_0_count_4')
_smoother_0_avg_4 = Int('_smoother_0_avg_4')

s_p_5 = Int('s_p_5')
s_OUT_value_5 = Real('s_OUT_value_5')
s_OUT_reqRead_5 = Bool('s_OUT_reqRead_5')
s_OUT_reqWrite_5 = Bool('s_OUT_reqWrite_5')
m_IN_value_5 = Real('m_IN_value_5')
m_IN_reqRead_5 = Bool('m_IN_reqRead_5')
m_IN_reqWrite_5 = Bool('m_IN_reqWrite_5')
_smoother_0_count_5 = Int('_smoother_0_count_5')
_smoother_0_avg_5 = Int('_smoother_0_avg_5')

s_p_6 = Int('s_p_6')
s_OUT_value_6 = Real('s_OUT_value_6')
s_OUT_reqRead_6 = Bool('s_OUT_reqRead_6')
s_OUT_reqWrite_6 = Bool('s_OUT_reqWrite_6')
m_IN_value_6 = Real('m_IN_value_6')
m_IN_reqRead_6 = Bool('m_IN_reqRead_6')
m_IN_reqWrite_6 = Bool('m_IN_reqWrite_6')
_smoother_0_count_6 = Int('_smoother_0_count_6')
_smoother_0_avg_6 = Int('_smoother_0_avg_6')

s_p_7 = Int('s_p_7')
s_OUT_value_7 = Real('s_OUT_value_7')
s_OUT_reqRead_7 = Bool('s_OUT_reqRead_7')
s_OUT_reqWrite_7 = Bool('s_OUT_reqWrite_7')
m_IN_value_7 = Real('m_IN_value_7')
m_IN_reqRead_7 = Bool('m_IN_reqRead_7')
m_IN_reqWrite_7 = Bool('m_IN_reqWrite_7')
_smoother_0_count_7 = Int('_smoother_0_count_7')
_smoother_0_avg_7 = Int('_smoother_0_avg_7')

s_p_8 = Int('s_p_8')
s_OUT_value_8 = Real('s_OUT_value_8')
s_OUT_reqRead_8 = Bool('s_OUT_reqRead_8')
s_OUT_reqWrite_8 = Bool('s_OUT_reqWrite_8')
m_IN_value_8 = Real('m_IN_value_8')
m_IN_reqRead_8 = Bool('m_IN_reqRead_8')
m_IN_reqWrite_8 = Bool('m_IN_reqWrite_8')
_smoother_0_count_8 = Int('_smoother_0_count_8')
_smoother_0_avg_8 = Int('_smoother_0_avg_8')

s_p_9 = Int('s_p_9')
s_OUT_value_9 = Real('s_OUT_value_9')
s_OUT_reqRead_9 = Bool('s_OUT_reqRead_9')
s_OUT_reqWrite_9 = Bool('s_OUT_reqWrite_9')
m_IN_value_9 = Real('m_IN_value_9')
m_IN_reqRead_9 = Bool('m_IN_reqRead_9')
m_IN_reqWrite_9 = Bool('m_IN_reqWrite_9')
_smoother_0_count_9 = Int('_smoother_0_count_9')
_smoother_0_avg_9 = Int('_smoother_0_avg_9')

s_p_10 = Int('s_p_10')
s_OUT_value_10 = Real('s_OUT_value_10')
s_OUT_reqRead_10 = Bool('s_OUT_reqRead_10')
s_OUT_reqWrite_10 = Bool('s_OUT_reqWrite_10')
m_IN_value_10 = Real('m_IN_value_10')
m_IN_reqRead_10 = Bool('m_IN_reqRead_10')
m_IN_reqWrite_10 = Bool('m_IN_reqWrite_10')
_smoother_0_count_10 = Int('_smoother_0_count_10')
_smoother_0_avg_10 = Int('_smoother_0_avg_10')

s_p_11 = Int('s_p_11')
s_OUT_value_11 = Real('s_OUT_value_11')
s_OUT_reqRead_11 = Bool('s_OUT_reqRead_11')
s_OUT_reqWrite_11 = Bool('s_OUT_reqWrite_11')
m_IN_value_11 = Real('m_IN_value_11')
m_IN_reqRead_11 = Bool('m_IN_reqRead_11')
m_IN_reqWrite_11 = Bool('m_IN_reqWrite_11')
_smoother_0_count_11 = Int('_smoother_0_count_11')
_smoother_0_avg_11 = Int('_smoother_0_avg_11')

s_p_12 = Int('s_p_12')
s_OUT_value_12 = Real('s_OUT_value_12')
s_OUT_reqRead_12 = Bool('s_OUT_reqRead_12')
s_OUT_reqWrite_12 = Bool('s_OUT_reqWrite_12')
m_IN_value_12 = Real('m_IN_value_12')
m_IN_reqRead_12 = Bool('m_IN_reqRead_12')
m_IN_reqWrite_12 = Bool('m_IN_reqWrite_12')
_smoother_0_count_12 = Int('_smoother_0_count_12')
_smoother_0_avg_12 = Int('_smoother_0_avg_12')

s_p_13 = Int('s_p_13')
s_OUT_value_13 = Real('s_OUT_value_13')
s_OUT_reqRead_13 = Bool('s_OUT_reqRead_13')
s_OUT_reqWrite_13 = Bool('s_OUT_reqWrite_13')
m_IN_value_13 = Real('m_IN_value_13')
m_IN_reqRead_13 = Bool('m_IN_reqRead_13')
m_IN_reqWrite_13 = Bool('m_IN_reqWrite_13')
_smoother_0_count_13 = Int('_smoother_0_count_13')
_smoother_0_avg_13 = Int('_smoother_0_avg_13')

s_p_14 = Int('s_p_14')
s_OUT_value_14 = Real('s_OUT_value_14')
s_OUT_reqRead_14 = Bool('s_OUT_reqRead_14')
s_OUT_reqWrite_14 = Bool('s_OUT_reqWrite_14')
m_IN_value_14 = Real('m_IN_value_14')
m_IN_reqRead_14 = Bool('m_IN_reqRead_14')
m_IN_reqWrite_14 = Bool('m_IN_reqWrite_14')
_smoother_0_count_14 = Int('_smoother_0_count_14')
_smoother_0_avg_14 = Int('_smoother_0_avg_14')

s_p_15 = Int('s_p_15')
s_OUT_value_15 = Real('s_OUT_value_15')
s_OUT_reqRead_15 = Bool('s_OUT_reqRead_15')
s_OUT_reqWrite_15 = Bool('s_OUT_reqWrite_15')
m_IN_value_15 = Real('m_IN_value_15')
m_IN_reqRead_15 = Bool('m_IN_reqRead_15')
m_IN_reqWrite_15 = Bool('m_IN_reqWrite_15')
_smoother_0_count_15 = Int('_smoother_0_count_15')
_smoother_0_avg_15 = Int('_smoother_0_avg_15')

s_p_16 = Int('s_p_16')
s_OUT_value_16 = Real('s_OUT_value_16')
s_OUT_reqRead_16 = Bool('s_OUT_reqRead_16')
s_OUT_reqWrite_16 = Bool('s_OUT_reqWrite_16')
m_IN_value_16 = Real('m_IN_value_16')
m_IN_reqRead_16 = Bool('m_IN_reqRead_16')
m_IN_reqWrite_16 = Bool('m_IN_reqWrite_16')
_smoother_0_count_16 = Int('_smoother_0_count_16')
_smoother_0_avg_16 = Int('_smoother_0_avg_16')

s_p_17 = Int('s_p_17')
s_OUT_value_17 = Real('s_OUT_value_17')
s_OUT_reqRead_17 = Bool('s_OUT_reqRead_17')
s_OUT_reqWrite_17 = Bool('s_OUT_reqWrite_17')
m_IN_value_17 = Real('m_IN_value_17')
m_IN_reqRead_17 = Bool('m_IN_reqRead_17')
m_IN_reqWrite_17 = Bool('m_IN_reqWrite_17')
_smoother_0_count_17 = Int('_smoother_0_count_17')
_smoother_0_avg_17 = Int('_smoother_0_avg_17')

s_p_18 = Int('s_p_18')
s_OUT_value_18 = Real('s_OUT_value_18')
s_OUT_reqRead_18 = Bool('s_OUT_reqRead_18')
s_OUT_reqWrite_18 = Bool('s_OUT_reqWrite_18')
m_IN_value_18 = Real('m_IN_value_18')
m_IN_reqRead_18 = Bool('m_IN_reqRead_18')
m_IN_reqWrite_18 = Bool('m_IN_reqWrite_18')
_smoother_0_count_18 = Int('_smoother_0_count_18')
_smoother_0_avg_18 = Int('_smoother_0_avg_18')

s_p_19 = Int('s_p_19')
s_OUT_value_19 = Real('s_OUT_value_19')
s_OUT_reqRead_19 = Bool('s_OUT_reqRead_19')
s_OUT_reqWrite_19 = Bool('s_OUT_reqWrite_19')
m_IN_value_19 = Real('m_IN_value_19')
m_IN_reqRead_19 = Bool('m_IN_reqRead_19')
m_IN_reqWrite_19 = Bool('m_IN_reqWrite_19')
_smoother_0_count_19 = Int('_smoother_0_count_19')
_smoother_0_avg_19 = Int('_smoother_0_avg_19')

s_p_20 = Int('s_p_20')
s_OUT_value_20 = Real('s_OUT_value_20')
s_OUT_reqRead_20 = Bool('s_OUT_reqRead_20')
s_OUT_reqWrite_20 = Bool('s_OUT_reqWrite_20')
m_IN_value_20 = Real('m_IN_value_20')
m_IN_reqRead_20 = Bool('m_IN_reqRead_20')
m_IN_reqWrite_20 = Bool('m_IN_reqWrite_20')
_smoother_0_count_20 = Int('_smoother_0_count_20')
_smoother_0_avg_20 = Int('_smoother_0_avg_20')

s = Solver()
s.add(s_p_0 == 0)
s.add(s_OUT_reqRead_0 == False)
s.add(s_OUT_reqWrite_0 == False)
s.add(m_IN_reqRead_0 == False)
s.add(m_IN_reqWrite_0 == False)
s.add(_smoother_0_count_0 == 5)
s.add(_smoother_0_avg_0 == 0)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_0 == s_OUT_reqWrite_0)), s_OUT_reqWrite_0 == s_OUT_reqRead_0, s_p_1 == s_p_0, _smoother_0_count_1 == _smoother_0_count_0, _smoother_0_avg_1 == _smoother_0_avg_0), And(And(Not(False), m_IN_reqRead_0 == False), m_IN_reqRead_0 == True, s_p_1 == s_p_0, _smoother_0_count_1 == _smoother_0_count_0, _smoother_0_avg_1 == _smoother_0_avg_0), And(And(Not(False), Not(s_OUT_reqRead_0 == And(s_OUT_reqWrite_0, _smoother_0_count_0 < 5))), s_OUT_reqRead_0 == And(s_OUT_reqWrite_0, _smoother_0_count_0 < 5), s_p_1 == s_p_0, _smoother_0_count_1 == _smoother_0_count_0, _smoother_0_avg_1 == _smoother_0_avg_0), And(And(Not(Or(False, Not(s_OUT_reqRead_0 == And(s_OUT_reqWrite_0, _smoother_0_count_0 < 5)))), Not(m_IN_reqWrite_0 == And(m_IN_reqRead_0, _smoother_0_count_0 == 5))), m_IN_reqWrite_0 == And(m_IN_reqRead_0, _smoother_0_count_0 == 5), s_p_1 == s_p_0, _smoother_0_count_1 == _smoother_0_count_0, _smoother_0_avg_1 == _smoother_0_avg_0), And(And(And(Not(Or(False, Not(s_OUT_reqRead_0 == s_OUT_reqWrite_0))), s_OUT_reqWrite_0), And(Not(Or(Or(False, Not(s_OUT_reqRead_0 == And(s_OUT_reqWrite_0, _smoother_0_count_0 < 5))), Not(m_IN_reqWrite_0 == And(m_IN_reqRead_0, _smoother_0_count_0 == 5)))), s_OUT_reqRead_0)), _smoother_0_count_1 == (_smoother_0_count_0 + 1), s_OUT_value_0 == s_p_0, s_OUT_reqWrite_0 == False, s_OUT_reqRead_0 == False, _smoother_0_avg_1 == (_smoother_0_avg_0 + s_OUT_value_0), s_p_1 == ((s_p_0 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_0 == False)), m_IN_reqWrite_0), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_0 == And(s_OUT_reqWrite_0, _smoother_0_count_0 < 5))), Not(m_IN_reqWrite_0 == And(m_IN_reqRead_0, _smoother_0_count_0 == 5))), s_OUT_reqRead_0)), m_IN_reqWrite_0)), _smoother_0_count_1 == 0, m_IN_value_0 == (to_real(_smoother_0_avg_0) / to_real(5)), m_IN_reqWrite_0 == False, m_IN_reqRead_0 == False, s_p_1 == s_p_0, _smoother_0_avg_1 == _smoother_0_avg_0))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_1 == s_OUT_reqWrite_1)), s_OUT_reqWrite_1 == s_OUT_reqRead_1, s_p_2 == s_p_1, _smoother_0_count_2 == _smoother_0_count_1, _smoother_0_avg_2 == _smoother_0_avg_1), And(And(Not(False), m_IN_reqRead_1 == False), m_IN_reqRead_1 == True, s_p_2 == s_p_1, _smoother_0_count_2 == _smoother_0_count_1, _smoother_0_avg_2 == _smoother_0_avg_1), And(And(Not(False), Not(s_OUT_reqRead_1 == And(s_OUT_reqWrite_1, _smoother_0_count_1 < 5))), s_OUT_reqRead_1 == And(s_OUT_reqWrite_1, _smoother_0_count_1 < 5), s_p_2 == s_p_1, _smoother_0_count_2 == _smoother_0_count_1, _smoother_0_avg_2 == _smoother_0_avg_1), And(And(Not(Or(False, Not(s_OUT_reqRead_1 == And(s_OUT_reqWrite_1, _smoother_0_count_1 < 5)))), Not(m_IN_reqWrite_1 == And(m_IN_reqRead_1, _smoother_0_count_1 == 5))), m_IN_reqWrite_1 == And(m_IN_reqRead_1, _smoother_0_count_1 == 5), s_p_2 == s_p_1, _smoother_0_count_2 == _smoother_0_count_1, _smoother_0_avg_2 == _smoother_0_avg_1), And(And(And(Not(Or(False, Not(s_OUT_reqRead_1 == s_OUT_reqWrite_1))), s_OUT_reqWrite_1), And(Not(Or(Or(False, Not(s_OUT_reqRead_1 == And(s_OUT_reqWrite_1, _smoother_0_count_1 < 5))), Not(m_IN_reqWrite_1 == And(m_IN_reqRead_1, _smoother_0_count_1 == 5)))), s_OUT_reqRead_1)), _smoother_0_count_2 == (_smoother_0_count_1 + 1), s_OUT_value_1 == s_p_1, s_OUT_reqWrite_1 == False, s_OUT_reqRead_1 == False, _smoother_0_avg_2 == (_smoother_0_avg_1 + s_OUT_value_1), s_p_2 == ((s_p_1 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_1 == False)), m_IN_reqWrite_1), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_1 == And(s_OUT_reqWrite_1, _smoother_0_count_1 < 5))), Not(m_IN_reqWrite_1 == And(m_IN_reqRead_1, _smoother_0_count_1 == 5))), s_OUT_reqRead_1)), m_IN_reqWrite_1)), _smoother_0_count_2 == 0, m_IN_value_1 == (to_real(_smoother_0_avg_1) / to_real(5)), m_IN_reqWrite_1 == False, m_IN_reqRead_1 == False, s_p_2 == s_p_1, _smoother_0_avg_2 == _smoother_0_avg_1))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_2 == s_OUT_reqWrite_2)), s_OUT_reqWrite_2 == s_OUT_reqRead_2, s_p_3 == s_p_2, _smoother_0_count_3 == _smoother_0_count_2, _smoother_0_avg_3 == _smoother_0_avg_2), And(And(Not(False), m_IN_reqRead_2 == False), m_IN_reqRead_2 == True, s_p_3 == s_p_2, _smoother_0_count_3 == _smoother_0_count_2, _smoother_0_avg_3 == _smoother_0_avg_2), And(And(Not(False), Not(s_OUT_reqRead_2 == And(s_OUT_reqWrite_2, _smoother_0_count_2 < 5))), s_OUT_reqRead_2 == And(s_OUT_reqWrite_2, _smoother_0_count_2 < 5), s_p_3 == s_p_2, _smoother_0_count_3 == _smoother_0_count_2, _smoother_0_avg_3 == _smoother_0_avg_2), And(And(Not(Or(False, Not(s_OUT_reqRead_2 == And(s_OUT_reqWrite_2, _smoother_0_count_2 < 5)))), Not(m_IN_reqWrite_2 == And(m_IN_reqRead_2, _smoother_0_count_2 == 5))), m_IN_reqWrite_2 == And(m_IN_reqRead_2, _smoother_0_count_2 == 5), s_p_3 == s_p_2, _smoother_0_count_3 == _smoother_0_count_2, _smoother_0_avg_3 == _smoother_0_avg_2), And(And(And(Not(Or(False, Not(s_OUT_reqRead_2 == s_OUT_reqWrite_2))), s_OUT_reqWrite_2), And(Not(Or(Or(False, Not(s_OUT_reqRead_2 == And(s_OUT_reqWrite_2, _smoother_0_count_2 < 5))), Not(m_IN_reqWrite_2 == And(m_IN_reqRead_2, _smoother_0_count_2 == 5)))), s_OUT_reqRead_2)), _smoother_0_count_3 == (_smoother_0_count_2 + 1), s_OUT_value_2 == s_p_2, s_OUT_reqWrite_2 == False, s_OUT_reqRead_2 == False, _smoother_0_avg_3 == (_smoother_0_avg_2 + s_OUT_value_2), s_p_3 == ((s_p_2 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_2 == False)), m_IN_reqWrite_2), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_2 == And(s_OUT_reqWrite_2, _smoother_0_count_2 < 5))), Not(m_IN_reqWrite_2 == And(m_IN_reqRead_2, _smoother_0_count_2 == 5))), s_OUT_reqRead_2)), m_IN_reqWrite_2)), _smoother_0_count_3 == 0, m_IN_value_2 == (to_real(_smoother_0_avg_2) / to_real(5)), m_IN_reqWrite_2 == False, m_IN_reqRead_2 == False, s_p_3 == s_p_2, _smoother_0_avg_3 == _smoother_0_avg_2))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_3 == s_OUT_reqWrite_3)), s_OUT_reqWrite_3 == s_OUT_reqRead_3, s_p_4 == s_p_3, _smoother_0_count_4 == _smoother_0_count_3, _smoother_0_avg_4 == _smoother_0_avg_3), And(And(Not(False), m_IN_reqRead_3 == False), m_IN_reqRead_3 == True, s_p_4 == s_p_3, _smoother_0_count_4 == _smoother_0_count_3, _smoother_0_avg_4 == _smoother_0_avg_3), And(And(Not(False), Not(s_OUT_reqRead_3 == And(s_OUT_reqWrite_3, _smoother_0_count_3 < 5))), s_OUT_reqRead_3 == And(s_OUT_reqWrite_3, _smoother_0_count_3 < 5), s_p_4 == s_p_3, _smoother_0_count_4 == _smoother_0_count_3, _smoother_0_avg_4 == _smoother_0_avg_3), And(And(Not(Or(False, Not(s_OUT_reqRead_3 == And(s_OUT_reqWrite_3, _smoother_0_count_3 < 5)))), Not(m_IN_reqWrite_3 == And(m_IN_reqRead_3, _smoother_0_count_3 == 5))), m_IN_reqWrite_3 == And(m_IN_reqRead_3, _smoother_0_count_3 == 5), s_p_4 == s_p_3, _smoother_0_count_4 == _smoother_0_count_3, _smoother_0_avg_4 == _smoother_0_avg_3), And(And(And(Not(Or(False, Not(s_OUT_reqRead_3 == s_OUT_reqWrite_3))), s_OUT_reqWrite_3), And(Not(Or(Or(False, Not(s_OUT_reqRead_3 == And(s_OUT_reqWrite_3, _smoother_0_count_3 < 5))), Not(m_IN_reqWrite_3 == And(m_IN_reqRead_3, _smoother_0_count_3 == 5)))), s_OUT_reqRead_3)), _smoother_0_count_4 == (_smoother_0_count_3 + 1), s_OUT_value_3 == s_p_3, s_OUT_reqWrite_3 == False, s_OUT_reqRead_3 == False, _smoother_0_avg_4 == (_smoother_0_avg_3 + s_OUT_value_3), s_p_4 == ((s_p_3 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_3 == False)), m_IN_reqWrite_3), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_3 == And(s_OUT_reqWrite_3, _smoother_0_count_3 < 5))), Not(m_IN_reqWrite_3 == And(m_IN_reqRead_3, _smoother_0_count_3 == 5))), s_OUT_reqRead_3)), m_IN_reqWrite_3)), _smoother_0_count_4 == 0, m_IN_value_3 == (to_real(_smoother_0_avg_3) / to_real(5)), m_IN_reqWrite_3 == False, m_IN_reqRead_3 == False, s_p_4 == s_p_3, _smoother_0_avg_4 == _smoother_0_avg_3))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_4 == s_OUT_reqWrite_4)), s_OUT_reqWrite_4 == s_OUT_reqRead_4, s_p_5 == s_p_4, _smoother_0_count_5 == _smoother_0_count_4, _smoother_0_avg_5 == _smoother_0_avg_4), And(And(Not(False), m_IN_reqRead_4 == False), m_IN_reqRead_4 == True, s_p_5 == s_p_4, _smoother_0_count_5 == _smoother_0_count_4, _smoother_0_avg_5 == _smoother_0_avg_4), And(And(Not(False), Not(s_OUT_reqRead_4 == And(s_OUT_reqWrite_4, _smoother_0_count_4 < 5))), s_OUT_reqRead_4 == And(s_OUT_reqWrite_4, _smoother_0_count_4 < 5), s_p_5 == s_p_4, _smoother_0_count_5 == _smoother_0_count_4, _smoother_0_avg_5 == _smoother_0_avg_4), And(And(Not(Or(False, Not(s_OUT_reqRead_4 == And(s_OUT_reqWrite_4, _smoother_0_count_4 < 5)))), Not(m_IN_reqWrite_4 == And(m_IN_reqRead_4, _smoother_0_count_4 == 5))), m_IN_reqWrite_4 == And(m_IN_reqRead_4, _smoother_0_count_4 == 5), s_p_5 == s_p_4, _smoother_0_count_5 == _smoother_0_count_4, _smoother_0_avg_5 == _smoother_0_avg_4), And(And(And(Not(Or(False, Not(s_OUT_reqRead_4 == s_OUT_reqWrite_4))), s_OUT_reqWrite_4), And(Not(Or(Or(False, Not(s_OUT_reqRead_4 == And(s_OUT_reqWrite_4, _smoother_0_count_4 < 5))), Not(m_IN_reqWrite_4 == And(m_IN_reqRead_4, _smoother_0_count_4 == 5)))), s_OUT_reqRead_4)), _smoother_0_count_5 == (_smoother_0_count_4 + 1), s_OUT_value_4 == s_p_4, s_OUT_reqWrite_4 == False, s_OUT_reqRead_4 == False, _smoother_0_avg_5 == (_smoother_0_avg_4 + s_OUT_value_4), s_p_5 == ((s_p_4 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_4 == False)), m_IN_reqWrite_4), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_4 == And(s_OUT_reqWrite_4, _smoother_0_count_4 < 5))), Not(m_IN_reqWrite_4 == And(m_IN_reqRead_4, _smoother_0_count_4 == 5))), s_OUT_reqRead_4)), m_IN_reqWrite_4)), _smoother_0_count_5 == 0, m_IN_value_4 == (to_real(_smoother_0_avg_4) / to_real(5)), m_IN_reqWrite_4 == False, m_IN_reqRead_4 == False, s_p_5 == s_p_4, _smoother_0_avg_5 == _smoother_0_avg_4))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_5 == s_OUT_reqWrite_5)), s_OUT_reqWrite_5 == s_OUT_reqRead_5, s_p_6 == s_p_5, _smoother_0_count_6 == _smoother_0_count_5, _smoother_0_avg_6 == _smoother_0_avg_5), And(And(Not(False), m_IN_reqRead_5 == False), m_IN_reqRead_5 == True, s_p_6 == s_p_5, _smoother_0_count_6 == _smoother_0_count_5, _smoother_0_avg_6 == _smoother_0_avg_5), And(And(Not(False), Not(s_OUT_reqRead_5 == And(s_OUT_reqWrite_5, _smoother_0_count_5 < 5))), s_OUT_reqRead_5 == And(s_OUT_reqWrite_5, _smoother_0_count_5 < 5), s_p_6 == s_p_5, _smoother_0_count_6 == _smoother_0_count_5, _smoother_0_avg_6 == _smoother_0_avg_5), And(And(Not(Or(False, Not(s_OUT_reqRead_5 == And(s_OUT_reqWrite_5, _smoother_0_count_5 < 5)))), Not(m_IN_reqWrite_5 == And(m_IN_reqRead_5, _smoother_0_count_5 == 5))), m_IN_reqWrite_5 == And(m_IN_reqRead_5, _smoother_0_count_5 == 5), s_p_6 == s_p_5, _smoother_0_count_6 == _smoother_0_count_5, _smoother_0_avg_6 == _smoother_0_avg_5), And(And(And(Not(Or(False, Not(s_OUT_reqRead_5 == s_OUT_reqWrite_5))), s_OUT_reqWrite_5), And(Not(Or(Or(False, Not(s_OUT_reqRead_5 == And(s_OUT_reqWrite_5, _smoother_0_count_5 < 5))), Not(m_IN_reqWrite_5 == And(m_IN_reqRead_5, _smoother_0_count_5 == 5)))), s_OUT_reqRead_5)), _smoother_0_count_6 == (_smoother_0_count_5 + 1), s_OUT_value_5 == s_p_5, s_OUT_reqWrite_5 == False, s_OUT_reqRead_5 == False, _smoother_0_avg_6 == (_smoother_0_avg_5 + s_OUT_value_5), s_p_6 == ((s_p_5 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_5 == False)), m_IN_reqWrite_5), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_5 == And(s_OUT_reqWrite_5, _smoother_0_count_5 < 5))), Not(m_IN_reqWrite_5 == And(m_IN_reqRead_5, _smoother_0_count_5 == 5))), s_OUT_reqRead_5)), m_IN_reqWrite_5)), _smoother_0_count_6 == 0, m_IN_value_5 == (to_real(_smoother_0_avg_5) / to_real(5)), m_IN_reqWrite_5 == False, m_IN_reqRead_5 == False, s_p_6 == s_p_5, _smoother_0_avg_6 == _smoother_0_avg_5))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_6 == s_OUT_reqWrite_6)), s_OUT_reqWrite_6 == s_OUT_reqRead_6, s_p_7 == s_p_6, _smoother_0_count_7 == _smoother_0_count_6, _smoother_0_avg_7 == _smoother_0_avg_6), And(And(Not(False), m_IN_reqRead_6 == False), m_IN_reqRead_6 == True, s_p_7 == s_p_6, _smoother_0_count_7 == _smoother_0_count_6, _smoother_0_avg_7 == _smoother_0_avg_6), And(And(Not(False), Not(s_OUT_reqRead_6 == And(s_OUT_reqWrite_6, _smoother_0_count_6 < 5))), s_OUT_reqRead_6 == And(s_OUT_reqWrite_6, _smoother_0_count_6 < 5), s_p_7 == s_p_6, _smoother_0_count_7 == _smoother_0_count_6, _smoother_0_avg_7 == _smoother_0_avg_6), And(And(Not(Or(False, Not(s_OUT_reqRead_6 == And(s_OUT_reqWrite_6, _smoother_0_count_6 < 5)))), Not(m_IN_reqWrite_6 == And(m_IN_reqRead_6, _smoother_0_count_6 == 5))), m_IN_reqWrite_6 == And(m_IN_reqRead_6, _smoother_0_count_6 == 5), s_p_7 == s_p_6, _smoother_0_count_7 == _smoother_0_count_6, _smoother_0_avg_7 == _smoother_0_avg_6), And(And(And(Not(Or(False, Not(s_OUT_reqRead_6 == s_OUT_reqWrite_6))), s_OUT_reqWrite_6), And(Not(Or(Or(False, Not(s_OUT_reqRead_6 == And(s_OUT_reqWrite_6, _smoother_0_count_6 < 5))), Not(m_IN_reqWrite_6 == And(m_IN_reqRead_6, _smoother_0_count_6 == 5)))), s_OUT_reqRead_6)), _smoother_0_count_7 == (_smoother_0_count_6 + 1), s_OUT_value_6 == s_p_6, s_OUT_reqWrite_6 == False, s_OUT_reqRead_6 == False, _smoother_0_avg_7 == (_smoother_0_avg_6 + s_OUT_value_6), s_p_7 == ((s_p_6 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_6 == False)), m_IN_reqWrite_6), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_6 == And(s_OUT_reqWrite_6, _smoother_0_count_6 < 5))), Not(m_IN_reqWrite_6 == And(m_IN_reqRead_6, _smoother_0_count_6 == 5))), s_OUT_reqRead_6)), m_IN_reqWrite_6)), _smoother_0_count_7 == 0, m_IN_value_6 == (to_real(_smoother_0_avg_6) / to_real(5)), m_IN_reqWrite_6 == False, m_IN_reqRead_6 == False, s_p_7 == s_p_6, _smoother_0_avg_7 == _smoother_0_avg_6))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_7 == s_OUT_reqWrite_7)), s_OUT_reqWrite_7 == s_OUT_reqRead_7, s_p_8 == s_p_7, _smoother_0_count_8 == _smoother_0_count_7, _smoother_0_avg_8 == _smoother_0_avg_7), And(And(Not(False), m_IN_reqRead_7 == False), m_IN_reqRead_7 == True, s_p_8 == s_p_7, _smoother_0_count_8 == _smoother_0_count_7, _smoother_0_avg_8 == _smoother_0_avg_7), And(And(Not(False), Not(s_OUT_reqRead_7 == And(s_OUT_reqWrite_7, _smoother_0_count_7 < 5))), s_OUT_reqRead_7 == And(s_OUT_reqWrite_7, _smoother_0_count_7 < 5), s_p_8 == s_p_7, _smoother_0_count_8 == _smoother_0_count_7, _smoother_0_avg_8 == _smoother_0_avg_7), And(And(Not(Or(False, Not(s_OUT_reqRead_7 == And(s_OUT_reqWrite_7, _smoother_0_count_7 < 5)))), Not(m_IN_reqWrite_7 == And(m_IN_reqRead_7, _smoother_0_count_7 == 5))), m_IN_reqWrite_7 == And(m_IN_reqRead_7, _smoother_0_count_7 == 5), s_p_8 == s_p_7, _smoother_0_count_8 == _smoother_0_count_7, _smoother_0_avg_8 == _smoother_0_avg_7), And(And(And(Not(Or(False, Not(s_OUT_reqRead_7 == s_OUT_reqWrite_7))), s_OUT_reqWrite_7), And(Not(Or(Or(False, Not(s_OUT_reqRead_7 == And(s_OUT_reqWrite_7, _smoother_0_count_7 < 5))), Not(m_IN_reqWrite_7 == And(m_IN_reqRead_7, _smoother_0_count_7 == 5)))), s_OUT_reqRead_7)), _smoother_0_count_8 == (_smoother_0_count_7 + 1), s_OUT_value_7 == s_p_7, s_OUT_reqWrite_7 == False, s_OUT_reqRead_7 == False, _smoother_0_avg_8 == (_smoother_0_avg_7 + s_OUT_value_7), s_p_8 == ((s_p_7 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_7 == False)), m_IN_reqWrite_7), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_7 == And(s_OUT_reqWrite_7, _smoother_0_count_7 < 5))), Not(m_IN_reqWrite_7 == And(m_IN_reqRead_7, _smoother_0_count_7 == 5))), s_OUT_reqRead_7)), m_IN_reqWrite_7)), _smoother_0_count_8 == 0, m_IN_value_7 == (to_real(_smoother_0_avg_7) / to_real(5)), m_IN_reqWrite_7 == False, m_IN_reqRead_7 == False, s_p_8 == s_p_7, _smoother_0_avg_8 == _smoother_0_avg_7))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_8 == s_OUT_reqWrite_8)), s_OUT_reqWrite_8 == s_OUT_reqRead_8, s_p_9 == s_p_8, _smoother_0_count_9 == _smoother_0_count_8, _smoother_0_avg_9 == _smoother_0_avg_8), And(And(Not(False), m_IN_reqRead_8 == False), m_IN_reqRead_8 == True, s_p_9 == s_p_8, _smoother_0_count_9 == _smoother_0_count_8, _smoother_0_avg_9 == _smoother_0_avg_8), And(And(Not(False), Not(s_OUT_reqRead_8 == And(s_OUT_reqWrite_8, _smoother_0_count_8 < 5))), s_OUT_reqRead_8 == And(s_OUT_reqWrite_8, _smoother_0_count_8 < 5), s_p_9 == s_p_8, _smoother_0_count_9 == _smoother_0_count_8, _smoother_0_avg_9 == _smoother_0_avg_8), And(And(Not(Or(False, Not(s_OUT_reqRead_8 == And(s_OUT_reqWrite_8, _smoother_0_count_8 < 5)))), Not(m_IN_reqWrite_8 == And(m_IN_reqRead_8, _smoother_0_count_8 == 5))), m_IN_reqWrite_8 == And(m_IN_reqRead_8, _smoother_0_count_8 == 5), s_p_9 == s_p_8, _smoother_0_count_9 == _smoother_0_count_8, _smoother_0_avg_9 == _smoother_0_avg_8), And(And(And(Not(Or(False, Not(s_OUT_reqRead_8 == s_OUT_reqWrite_8))), s_OUT_reqWrite_8), And(Not(Or(Or(False, Not(s_OUT_reqRead_8 == And(s_OUT_reqWrite_8, _smoother_0_count_8 < 5))), Not(m_IN_reqWrite_8 == And(m_IN_reqRead_8, _smoother_0_count_8 == 5)))), s_OUT_reqRead_8)), _smoother_0_count_9 == (_smoother_0_count_8 + 1), s_OUT_value_8 == s_p_8, s_OUT_reqWrite_8 == False, s_OUT_reqRead_8 == False, _smoother_0_avg_9 == (_smoother_0_avg_8 + s_OUT_value_8), s_p_9 == ((s_p_8 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_8 == False)), m_IN_reqWrite_8), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_8 == And(s_OUT_reqWrite_8, _smoother_0_count_8 < 5))), Not(m_IN_reqWrite_8 == And(m_IN_reqRead_8, _smoother_0_count_8 == 5))), s_OUT_reqRead_8)), m_IN_reqWrite_8)), _smoother_0_count_9 == 0, m_IN_value_8 == (to_real(_smoother_0_avg_8) / to_real(5)), m_IN_reqWrite_8 == False, m_IN_reqRead_8 == False, s_p_9 == s_p_8, _smoother_0_avg_9 == _smoother_0_avg_8))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_9 == s_OUT_reqWrite_9)), s_OUT_reqWrite_9 == s_OUT_reqRead_9, s_p_10 == s_p_9, _smoother_0_count_10 == _smoother_0_count_9, _smoother_0_avg_10 == _smoother_0_avg_9), And(And(Not(False), m_IN_reqRead_9 == False), m_IN_reqRead_9 == True, s_p_10 == s_p_9, _smoother_0_count_10 == _smoother_0_count_9, _smoother_0_avg_10 == _smoother_0_avg_9), And(And(Not(False), Not(s_OUT_reqRead_9 == And(s_OUT_reqWrite_9, _smoother_0_count_9 < 5))), s_OUT_reqRead_9 == And(s_OUT_reqWrite_9, _smoother_0_count_9 < 5), s_p_10 == s_p_9, _smoother_0_count_10 == _smoother_0_count_9, _smoother_0_avg_10 == _smoother_0_avg_9), And(And(Not(Or(False, Not(s_OUT_reqRead_9 == And(s_OUT_reqWrite_9, _smoother_0_count_9 < 5)))), Not(m_IN_reqWrite_9 == And(m_IN_reqRead_9, _smoother_0_count_9 == 5))), m_IN_reqWrite_9 == And(m_IN_reqRead_9, _smoother_0_count_9 == 5), s_p_10 == s_p_9, _smoother_0_count_10 == _smoother_0_count_9, _smoother_0_avg_10 == _smoother_0_avg_9), And(And(And(Not(Or(False, Not(s_OUT_reqRead_9 == s_OUT_reqWrite_9))), s_OUT_reqWrite_9), And(Not(Or(Or(False, Not(s_OUT_reqRead_9 == And(s_OUT_reqWrite_9, _smoother_0_count_9 < 5))), Not(m_IN_reqWrite_9 == And(m_IN_reqRead_9, _smoother_0_count_9 == 5)))), s_OUT_reqRead_9)), _smoother_0_count_10 == (_smoother_0_count_9 + 1), s_OUT_value_9 == s_p_9, s_OUT_reqWrite_9 == False, s_OUT_reqRead_9 == False, _smoother_0_avg_10 == (_smoother_0_avg_9 + s_OUT_value_9), s_p_10 == ((s_p_9 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_9 == False)), m_IN_reqWrite_9), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_9 == And(s_OUT_reqWrite_9, _smoother_0_count_9 < 5))), Not(m_IN_reqWrite_9 == And(m_IN_reqRead_9, _smoother_0_count_9 == 5))), s_OUT_reqRead_9)), m_IN_reqWrite_9)), _smoother_0_count_10 == 0, m_IN_value_9 == (to_real(_smoother_0_avg_9) / to_real(5)), m_IN_reqWrite_9 == False, m_IN_reqRead_9 == False, s_p_10 == s_p_9, _smoother_0_avg_10 == _smoother_0_avg_9))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_10 == s_OUT_reqWrite_10)), s_OUT_reqWrite_10 == s_OUT_reqRead_10, s_p_11 == s_p_10, _smoother_0_count_11 == _smoother_0_count_10, _smoother_0_avg_11 == _smoother_0_avg_10), And(And(Not(False), m_IN_reqRead_10 == False), m_IN_reqRead_10 == True, s_p_11 == s_p_10, _smoother_0_count_11 == _smoother_0_count_10, _smoother_0_avg_11 == _smoother_0_avg_10), And(And(Not(False), Not(s_OUT_reqRead_10 == And(s_OUT_reqWrite_10, _smoother_0_count_10 < 5))), s_OUT_reqRead_10 == And(s_OUT_reqWrite_10, _smoother_0_count_10 < 5), s_p_11 == s_p_10, _smoother_0_count_11 == _smoother_0_count_10, _smoother_0_avg_11 == _smoother_0_avg_10), And(And(Not(Or(False, Not(s_OUT_reqRead_10 == And(s_OUT_reqWrite_10, _smoother_0_count_10 < 5)))), Not(m_IN_reqWrite_10 == And(m_IN_reqRead_10, _smoother_0_count_10 == 5))), m_IN_reqWrite_10 == And(m_IN_reqRead_10, _smoother_0_count_10 == 5), s_p_11 == s_p_10, _smoother_0_count_11 == _smoother_0_count_10, _smoother_0_avg_11 == _smoother_0_avg_10), And(And(And(Not(Or(False, Not(s_OUT_reqRead_10 == s_OUT_reqWrite_10))), s_OUT_reqWrite_10), And(Not(Or(Or(False, Not(s_OUT_reqRead_10 == And(s_OUT_reqWrite_10, _smoother_0_count_10 < 5))), Not(m_IN_reqWrite_10 == And(m_IN_reqRead_10, _smoother_0_count_10 == 5)))), s_OUT_reqRead_10)), _smoother_0_count_11 == (_smoother_0_count_10 + 1), s_OUT_value_10 == s_p_10, s_OUT_reqWrite_10 == False, s_OUT_reqRead_10 == False, _smoother_0_avg_11 == (_smoother_0_avg_10 + s_OUT_value_10), s_p_11 == ((s_p_10 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_10 == False)), m_IN_reqWrite_10), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_10 == And(s_OUT_reqWrite_10, _smoother_0_count_10 < 5))), Not(m_IN_reqWrite_10 == And(m_IN_reqRead_10, _smoother_0_count_10 == 5))), s_OUT_reqRead_10)), m_IN_reqWrite_10)), _smoother_0_count_11 == 0, m_IN_value_10 == (to_real(_smoother_0_avg_10) / to_real(5)), m_IN_reqWrite_10 == False, m_IN_reqRead_10 == False, s_p_11 == s_p_10, _smoother_0_avg_11 == _smoother_0_avg_10))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_11 == s_OUT_reqWrite_11)), s_OUT_reqWrite_11 == s_OUT_reqRead_11, s_p_12 == s_p_11, _smoother_0_count_12 == _smoother_0_count_11, _smoother_0_avg_12 == _smoother_0_avg_11), And(And(Not(False), m_IN_reqRead_11 == False), m_IN_reqRead_11 == True, s_p_12 == s_p_11, _smoother_0_count_12 == _smoother_0_count_11, _smoother_0_avg_12 == _smoother_0_avg_11), And(And(Not(False), Not(s_OUT_reqRead_11 == And(s_OUT_reqWrite_11, _smoother_0_count_11 < 5))), s_OUT_reqRead_11 == And(s_OUT_reqWrite_11, _smoother_0_count_11 < 5), s_p_12 == s_p_11, _smoother_0_count_12 == _smoother_0_count_11, _smoother_0_avg_12 == _smoother_0_avg_11), And(And(Not(Or(False, Not(s_OUT_reqRead_11 == And(s_OUT_reqWrite_11, _smoother_0_count_11 < 5)))), Not(m_IN_reqWrite_11 == And(m_IN_reqRead_11, _smoother_0_count_11 == 5))), m_IN_reqWrite_11 == And(m_IN_reqRead_11, _smoother_0_count_11 == 5), s_p_12 == s_p_11, _smoother_0_count_12 == _smoother_0_count_11, _smoother_0_avg_12 == _smoother_0_avg_11), And(And(And(Not(Or(False, Not(s_OUT_reqRead_11 == s_OUT_reqWrite_11))), s_OUT_reqWrite_11), And(Not(Or(Or(False, Not(s_OUT_reqRead_11 == And(s_OUT_reqWrite_11, _smoother_0_count_11 < 5))), Not(m_IN_reqWrite_11 == And(m_IN_reqRead_11, _smoother_0_count_11 == 5)))), s_OUT_reqRead_11)), _smoother_0_count_12 == (_smoother_0_count_11 + 1), s_OUT_value_11 == s_p_11, s_OUT_reqWrite_11 == False, s_OUT_reqRead_11 == False, _smoother_0_avg_12 == (_smoother_0_avg_11 + s_OUT_value_11), s_p_12 == ((s_p_11 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_11 == False)), m_IN_reqWrite_11), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_11 == And(s_OUT_reqWrite_11, _smoother_0_count_11 < 5))), Not(m_IN_reqWrite_11 == And(m_IN_reqRead_11, _smoother_0_count_11 == 5))), s_OUT_reqRead_11)), m_IN_reqWrite_11)), _smoother_0_count_12 == 0, m_IN_value_11 == (to_real(_smoother_0_avg_11) / to_real(5)), m_IN_reqWrite_11 == False, m_IN_reqRead_11 == False, s_p_12 == s_p_11, _smoother_0_avg_12 == _smoother_0_avg_11))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_12 == s_OUT_reqWrite_12)), s_OUT_reqWrite_12 == s_OUT_reqRead_12, s_p_13 == s_p_12, _smoother_0_count_13 == _smoother_0_count_12, _smoother_0_avg_13 == _smoother_0_avg_12), And(And(Not(False), m_IN_reqRead_12 == False), m_IN_reqRead_12 == True, s_p_13 == s_p_12, _smoother_0_count_13 == _smoother_0_count_12, _smoother_0_avg_13 == _smoother_0_avg_12), And(And(Not(False), Not(s_OUT_reqRead_12 == And(s_OUT_reqWrite_12, _smoother_0_count_12 < 5))), s_OUT_reqRead_12 == And(s_OUT_reqWrite_12, _smoother_0_count_12 < 5), s_p_13 == s_p_12, _smoother_0_count_13 == _smoother_0_count_12, _smoother_0_avg_13 == _smoother_0_avg_12), And(And(Not(Or(False, Not(s_OUT_reqRead_12 == And(s_OUT_reqWrite_12, _smoother_0_count_12 < 5)))), Not(m_IN_reqWrite_12 == And(m_IN_reqRead_12, _smoother_0_count_12 == 5))), m_IN_reqWrite_12 == And(m_IN_reqRead_12, _smoother_0_count_12 == 5), s_p_13 == s_p_12, _smoother_0_count_13 == _smoother_0_count_12, _smoother_0_avg_13 == _smoother_0_avg_12), And(And(And(Not(Or(False, Not(s_OUT_reqRead_12 == s_OUT_reqWrite_12))), s_OUT_reqWrite_12), And(Not(Or(Or(False, Not(s_OUT_reqRead_12 == And(s_OUT_reqWrite_12, _smoother_0_count_12 < 5))), Not(m_IN_reqWrite_12 == And(m_IN_reqRead_12, _smoother_0_count_12 == 5)))), s_OUT_reqRead_12)), _smoother_0_count_13 == (_smoother_0_count_12 + 1), s_OUT_value_12 == s_p_12, s_OUT_reqWrite_12 == False, s_OUT_reqRead_12 == False, _smoother_0_avg_13 == (_smoother_0_avg_12 + s_OUT_value_12), s_p_13 == ((s_p_12 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_12 == False)), m_IN_reqWrite_12), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_12 == And(s_OUT_reqWrite_12, _smoother_0_count_12 < 5))), Not(m_IN_reqWrite_12 == And(m_IN_reqRead_12, _smoother_0_count_12 == 5))), s_OUT_reqRead_12)), m_IN_reqWrite_12)), _smoother_0_count_13 == 0, m_IN_value_12 == (to_real(_smoother_0_avg_12) / to_real(5)), m_IN_reqWrite_12 == False, m_IN_reqRead_12 == False, s_p_13 == s_p_12, _smoother_0_avg_13 == _smoother_0_avg_12))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_13 == s_OUT_reqWrite_13)), s_OUT_reqWrite_13 == s_OUT_reqRead_13, s_p_14 == s_p_13, _smoother_0_count_14 == _smoother_0_count_13, _smoother_0_avg_14 == _smoother_0_avg_13), And(And(Not(False), m_IN_reqRead_13 == False), m_IN_reqRead_13 == True, s_p_14 == s_p_13, _smoother_0_count_14 == _smoother_0_count_13, _smoother_0_avg_14 == _smoother_0_avg_13), And(And(Not(False), Not(s_OUT_reqRead_13 == And(s_OUT_reqWrite_13, _smoother_0_count_13 < 5))), s_OUT_reqRead_13 == And(s_OUT_reqWrite_13, _smoother_0_count_13 < 5), s_p_14 == s_p_13, _smoother_0_count_14 == _smoother_0_count_13, _smoother_0_avg_14 == _smoother_0_avg_13), And(And(Not(Or(False, Not(s_OUT_reqRead_13 == And(s_OUT_reqWrite_13, _smoother_0_count_13 < 5)))), Not(m_IN_reqWrite_13 == And(m_IN_reqRead_13, _smoother_0_count_13 == 5))), m_IN_reqWrite_13 == And(m_IN_reqRead_13, _smoother_0_count_13 == 5), s_p_14 == s_p_13, _smoother_0_count_14 == _smoother_0_count_13, _smoother_0_avg_14 == _smoother_0_avg_13), And(And(And(Not(Or(False, Not(s_OUT_reqRead_13 == s_OUT_reqWrite_13))), s_OUT_reqWrite_13), And(Not(Or(Or(False, Not(s_OUT_reqRead_13 == And(s_OUT_reqWrite_13, _smoother_0_count_13 < 5))), Not(m_IN_reqWrite_13 == And(m_IN_reqRead_13, _smoother_0_count_13 == 5)))), s_OUT_reqRead_13)), _smoother_0_count_14 == (_smoother_0_count_13 + 1), s_OUT_value_13 == s_p_13, s_OUT_reqWrite_13 == False, s_OUT_reqRead_13 == False, _smoother_0_avg_14 == (_smoother_0_avg_13 + s_OUT_value_13), s_p_14 == ((s_p_13 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_13 == False)), m_IN_reqWrite_13), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_13 == And(s_OUT_reqWrite_13, _smoother_0_count_13 < 5))), Not(m_IN_reqWrite_13 == And(m_IN_reqRead_13, _smoother_0_count_13 == 5))), s_OUT_reqRead_13)), m_IN_reqWrite_13)), _smoother_0_count_14 == 0, m_IN_value_13 == (to_real(_smoother_0_avg_13) / to_real(5)), m_IN_reqWrite_13 == False, m_IN_reqRead_13 == False, s_p_14 == s_p_13, _smoother_0_avg_14 == _smoother_0_avg_13))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_14 == s_OUT_reqWrite_14)), s_OUT_reqWrite_14 == s_OUT_reqRead_14, s_p_15 == s_p_14, _smoother_0_count_15 == _smoother_0_count_14, _smoother_0_avg_15 == _smoother_0_avg_14), And(And(Not(False), m_IN_reqRead_14 == False), m_IN_reqRead_14 == True, s_p_15 == s_p_14, _smoother_0_count_15 == _smoother_0_count_14, _smoother_0_avg_15 == _smoother_0_avg_14), And(And(Not(False), Not(s_OUT_reqRead_14 == And(s_OUT_reqWrite_14, _smoother_0_count_14 < 5))), s_OUT_reqRead_14 == And(s_OUT_reqWrite_14, _smoother_0_count_14 < 5), s_p_15 == s_p_14, _smoother_0_count_15 == _smoother_0_count_14, _smoother_0_avg_15 == _smoother_0_avg_14), And(And(Not(Or(False, Not(s_OUT_reqRead_14 == And(s_OUT_reqWrite_14, _smoother_0_count_14 < 5)))), Not(m_IN_reqWrite_14 == And(m_IN_reqRead_14, _smoother_0_count_14 == 5))), m_IN_reqWrite_14 == And(m_IN_reqRead_14, _smoother_0_count_14 == 5), s_p_15 == s_p_14, _smoother_0_count_15 == _smoother_0_count_14, _smoother_0_avg_15 == _smoother_0_avg_14), And(And(And(Not(Or(False, Not(s_OUT_reqRead_14 == s_OUT_reqWrite_14))), s_OUT_reqWrite_14), And(Not(Or(Or(False, Not(s_OUT_reqRead_14 == And(s_OUT_reqWrite_14, _smoother_0_count_14 < 5))), Not(m_IN_reqWrite_14 == And(m_IN_reqRead_14, _smoother_0_count_14 == 5)))), s_OUT_reqRead_14)), _smoother_0_count_15 == (_smoother_0_count_14 + 1), s_OUT_value_14 == s_p_14, s_OUT_reqWrite_14 == False, s_OUT_reqRead_14 == False, _smoother_0_avg_15 == (_smoother_0_avg_14 + s_OUT_value_14), s_p_15 == ((s_p_14 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_14 == False)), m_IN_reqWrite_14), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_14 == And(s_OUT_reqWrite_14, _smoother_0_count_14 < 5))), Not(m_IN_reqWrite_14 == And(m_IN_reqRead_14, _smoother_0_count_14 == 5))), s_OUT_reqRead_14)), m_IN_reqWrite_14)), _smoother_0_count_15 == 0, m_IN_value_14 == (to_real(_smoother_0_avg_14) / to_real(5)), m_IN_reqWrite_14 == False, m_IN_reqRead_14 == False, s_p_15 == s_p_14, _smoother_0_avg_15 == _smoother_0_avg_14))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_15 == s_OUT_reqWrite_15)), s_OUT_reqWrite_15 == s_OUT_reqRead_15, s_p_16 == s_p_15, _smoother_0_count_16 == _smoother_0_count_15, _smoother_0_avg_16 == _smoother_0_avg_15), And(And(Not(False), m_IN_reqRead_15 == False), m_IN_reqRead_15 == True, s_p_16 == s_p_15, _smoother_0_count_16 == _smoother_0_count_15, _smoother_0_avg_16 == _smoother_0_avg_15), And(And(Not(False), Not(s_OUT_reqRead_15 == And(s_OUT_reqWrite_15, _smoother_0_count_15 < 5))), s_OUT_reqRead_15 == And(s_OUT_reqWrite_15, _smoother_0_count_15 < 5), s_p_16 == s_p_15, _smoother_0_count_16 == _smoother_0_count_15, _smoother_0_avg_16 == _smoother_0_avg_15), And(And(Not(Or(False, Not(s_OUT_reqRead_15 == And(s_OUT_reqWrite_15, _smoother_0_count_15 < 5)))), Not(m_IN_reqWrite_15 == And(m_IN_reqRead_15, _smoother_0_count_15 == 5))), m_IN_reqWrite_15 == And(m_IN_reqRead_15, _smoother_0_count_15 == 5), s_p_16 == s_p_15, _smoother_0_count_16 == _smoother_0_count_15, _smoother_0_avg_16 == _smoother_0_avg_15), And(And(And(Not(Or(False, Not(s_OUT_reqRead_15 == s_OUT_reqWrite_15))), s_OUT_reqWrite_15), And(Not(Or(Or(False, Not(s_OUT_reqRead_15 == And(s_OUT_reqWrite_15, _smoother_0_count_15 < 5))), Not(m_IN_reqWrite_15 == And(m_IN_reqRead_15, _smoother_0_count_15 == 5)))), s_OUT_reqRead_15)), _smoother_0_count_16 == (_smoother_0_count_15 + 1), s_OUT_value_15 == s_p_15, s_OUT_reqWrite_15 == False, s_OUT_reqRead_15 == False, _smoother_0_avg_16 == (_smoother_0_avg_15 + s_OUT_value_15), s_p_16 == ((s_p_15 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_15 == False)), m_IN_reqWrite_15), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_15 == And(s_OUT_reqWrite_15, _smoother_0_count_15 < 5))), Not(m_IN_reqWrite_15 == And(m_IN_reqRead_15, _smoother_0_count_15 == 5))), s_OUT_reqRead_15)), m_IN_reqWrite_15)), _smoother_0_count_16 == 0, m_IN_value_15 == (to_real(_smoother_0_avg_15) / to_real(5)), m_IN_reqWrite_15 == False, m_IN_reqRead_15 == False, s_p_16 == s_p_15, _smoother_0_avg_16 == _smoother_0_avg_15))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_16 == s_OUT_reqWrite_16)), s_OUT_reqWrite_16 == s_OUT_reqRead_16, s_p_17 == s_p_16, _smoother_0_count_17 == _smoother_0_count_16, _smoother_0_avg_17 == _smoother_0_avg_16), And(And(Not(False), m_IN_reqRead_16 == False), m_IN_reqRead_16 == True, s_p_17 == s_p_16, _smoother_0_count_17 == _smoother_0_count_16, _smoother_0_avg_17 == _smoother_0_avg_16), And(And(Not(False), Not(s_OUT_reqRead_16 == And(s_OUT_reqWrite_16, _smoother_0_count_16 < 5))), s_OUT_reqRead_16 == And(s_OUT_reqWrite_16, _smoother_0_count_16 < 5), s_p_17 == s_p_16, _smoother_0_count_17 == _smoother_0_count_16, _smoother_0_avg_17 == _smoother_0_avg_16), And(And(Not(Or(False, Not(s_OUT_reqRead_16 == And(s_OUT_reqWrite_16, _smoother_0_count_16 < 5)))), Not(m_IN_reqWrite_16 == And(m_IN_reqRead_16, _smoother_0_count_16 == 5))), m_IN_reqWrite_16 == And(m_IN_reqRead_16, _smoother_0_count_16 == 5), s_p_17 == s_p_16, _smoother_0_count_17 == _smoother_0_count_16, _smoother_0_avg_17 == _smoother_0_avg_16), And(And(And(Not(Or(False, Not(s_OUT_reqRead_16 == s_OUT_reqWrite_16))), s_OUT_reqWrite_16), And(Not(Or(Or(False, Not(s_OUT_reqRead_16 == And(s_OUT_reqWrite_16, _smoother_0_count_16 < 5))), Not(m_IN_reqWrite_16 == And(m_IN_reqRead_16, _smoother_0_count_16 == 5)))), s_OUT_reqRead_16)), _smoother_0_count_17 == (_smoother_0_count_16 + 1), s_OUT_value_16 == s_p_16, s_OUT_reqWrite_16 == False, s_OUT_reqRead_16 == False, _smoother_0_avg_17 == (_smoother_0_avg_16 + s_OUT_value_16), s_p_17 == ((s_p_16 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_16 == False)), m_IN_reqWrite_16), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_16 == And(s_OUT_reqWrite_16, _smoother_0_count_16 < 5))), Not(m_IN_reqWrite_16 == And(m_IN_reqRead_16, _smoother_0_count_16 == 5))), s_OUT_reqRead_16)), m_IN_reqWrite_16)), _smoother_0_count_17 == 0, m_IN_value_16 == (to_real(_smoother_0_avg_16) / to_real(5)), m_IN_reqWrite_16 == False, m_IN_reqRead_16 == False, s_p_17 == s_p_16, _smoother_0_avg_17 == _smoother_0_avg_16))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_17 == s_OUT_reqWrite_17)), s_OUT_reqWrite_17 == s_OUT_reqRead_17, s_p_18 == s_p_17, _smoother_0_count_18 == _smoother_0_count_17, _smoother_0_avg_18 == _smoother_0_avg_17), And(And(Not(False), m_IN_reqRead_17 == False), m_IN_reqRead_17 == True, s_p_18 == s_p_17, _smoother_0_count_18 == _smoother_0_count_17, _smoother_0_avg_18 == _smoother_0_avg_17), And(And(Not(False), Not(s_OUT_reqRead_17 == And(s_OUT_reqWrite_17, _smoother_0_count_17 < 5))), s_OUT_reqRead_17 == And(s_OUT_reqWrite_17, _smoother_0_count_17 < 5), s_p_18 == s_p_17, _smoother_0_count_18 == _smoother_0_count_17, _smoother_0_avg_18 == _smoother_0_avg_17), And(And(Not(Or(False, Not(s_OUT_reqRead_17 == And(s_OUT_reqWrite_17, _smoother_0_count_17 < 5)))), Not(m_IN_reqWrite_17 == And(m_IN_reqRead_17, _smoother_0_count_17 == 5))), m_IN_reqWrite_17 == And(m_IN_reqRead_17, _smoother_0_count_17 == 5), s_p_18 == s_p_17, _smoother_0_count_18 == _smoother_0_count_17, _smoother_0_avg_18 == _smoother_0_avg_17), And(And(And(Not(Or(False, Not(s_OUT_reqRead_17 == s_OUT_reqWrite_17))), s_OUT_reqWrite_17), And(Not(Or(Or(False, Not(s_OUT_reqRead_17 == And(s_OUT_reqWrite_17, _smoother_0_count_17 < 5))), Not(m_IN_reqWrite_17 == And(m_IN_reqRead_17, _smoother_0_count_17 == 5)))), s_OUT_reqRead_17)), _smoother_0_count_18 == (_smoother_0_count_17 + 1), s_OUT_value_17 == s_p_17, s_OUT_reqWrite_17 == False, s_OUT_reqRead_17 == False, _smoother_0_avg_18 == (_smoother_0_avg_17 + s_OUT_value_17), s_p_18 == ((s_p_17 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_17 == False)), m_IN_reqWrite_17), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_17 == And(s_OUT_reqWrite_17, _smoother_0_count_17 < 5))), Not(m_IN_reqWrite_17 == And(m_IN_reqRead_17, _smoother_0_count_17 == 5))), s_OUT_reqRead_17)), m_IN_reqWrite_17)), _smoother_0_count_18 == 0, m_IN_value_17 == (to_real(_smoother_0_avg_17) / to_real(5)), m_IN_reqWrite_17 == False, m_IN_reqRead_17 == False, s_p_18 == s_p_17, _smoother_0_avg_18 == _smoother_0_avg_17))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_18 == s_OUT_reqWrite_18)), s_OUT_reqWrite_18 == s_OUT_reqRead_18, s_p_19 == s_p_18, _smoother_0_count_19 == _smoother_0_count_18, _smoother_0_avg_19 == _smoother_0_avg_18), And(And(Not(False), m_IN_reqRead_18 == False), m_IN_reqRead_18 == True, s_p_19 == s_p_18, _smoother_0_count_19 == _smoother_0_count_18, _smoother_0_avg_19 == _smoother_0_avg_18), And(And(Not(False), Not(s_OUT_reqRead_18 == And(s_OUT_reqWrite_18, _smoother_0_count_18 < 5))), s_OUT_reqRead_18 == And(s_OUT_reqWrite_18, _smoother_0_count_18 < 5), s_p_19 == s_p_18, _smoother_0_count_19 == _smoother_0_count_18, _smoother_0_avg_19 == _smoother_0_avg_18), And(And(Not(Or(False, Not(s_OUT_reqRead_18 == And(s_OUT_reqWrite_18, _smoother_0_count_18 < 5)))), Not(m_IN_reqWrite_18 == And(m_IN_reqRead_18, _smoother_0_count_18 == 5))), m_IN_reqWrite_18 == And(m_IN_reqRead_18, _smoother_0_count_18 == 5), s_p_19 == s_p_18, _smoother_0_count_19 == _smoother_0_count_18, _smoother_0_avg_19 == _smoother_0_avg_18), And(And(And(Not(Or(False, Not(s_OUT_reqRead_18 == s_OUT_reqWrite_18))), s_OUT_reqWrite_18), And(Not(Or(Or(False, Not(s_OUT_reqRead_18 == And(s_OUT_reqWrite_18, _smoother_0_count_18 < 5))), Not(m_IN_reqWrite_18 == And(m_IN_reqRead_18, _smoother_0_count_18 == 5)))), s_OUT_reqRead_18)), _smoother_0_count_19 == (_smoother_0_count_18 + 1), s_OUT_value_18 == s_p_18, s_OUT_reqWrite_18 == False, s_OUT_reqRead_18 == False, _smoother_0_avg_19 == (_smoother_0_avg_18 + s_OUT_value_18), s_p_19 == ((s_p_18 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_18 == False)), m_IN_reqWrite_18), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_18 == And(s_OUT_reqWrite_18, _smoother_0_count_18 < 5))), Not(m_IN_reqWrite_18 == And(m_IN_reqRead_18, _smoother_0_count_18 == 5))), s_OUT_reqRead_18)), m_IN_reqWrite_18)), _smoother_0_count_19 == 0, m_IN_value_18 == (to_real(_smoother_0_avg_18) / to_real(5)), m_IN_reqWrite_18 == False, m_IN_reqRead_18 == False, s_p_19 == s_p_18, _smoother_0_avg_19 == _smoother_0_avg_18))
)

s.add(Or(And(And(Not(False), Not(s_OUT_reqRead_19 == s_OUT_reqWrite_19)), s_OUT_reqWrite_19 == s_OUT_reqRead_19, s_p_20 == s_p_19, _smoother_0_count_20 == _smoother_0_count_19, _smoother_0_avg_20 == _smoother_0_avg_19), And(And(Not(False), m_IN_reqRead_19 == False), m_IN_reqRead_19 == True, s_p_20 == s_p_19, _smoother_0_count_20 == _smoother_0_count_19, _smoother_0_avg_20 == _smoother_0_avg_19), And(And(Not(False), Not(s_OUT_reqRead_19 == And(s_OUT_reqWrite_19, _smoother_0_count_19 < 5))), s_OUT_reqRead_19 == And(s_OUT_reqWrite_19, _smoother_0_count_19 < 5), s_p_20 == s_p_19, _smoother_0_count_20 == _smoother_0_count_19, _smoother_0_avg_20 == _smoother_0_avg_19), And(And(Not(Or(False, Not(s_OUT_reqRead_19 == And(s_OUT_reqWrite_19, _smoother_0_count_19 < 5)))), Not(m_IN_reqWrite_19 == And(m_IN_reqRead_19, _smoother_0_count_19 == 5))), m_IN_reqWrite_19 == And(m_IN_reqRead_19, _smoother_0_count_19 == 5), s_p_20 == s_p_19, _smoother_0_count_20 == _smoother_0_count_19, _smoother_0_avg_20 == _smoother_0_avg_19), And(And(And(Not(Or(False, Not(s_OUT_reqRead_19 == s_OUT_reqWrite_19))), s_OUT_reqWrite_19), And(Not(Or(Or(False, Not(s_OUT_reqRead_19 == And(s_OUT_reqWrite_19, _smoother_0_count_19 < 5))), Not(m_IN_reqWrite_19 == And(m_IN_reqRead_19, _smoother_0_count_19 == 5)))), s_OUT_reqRead_19)), _smoother_0_count_20 == (_smoother_0_count_19 + 1), s_OUT_value_19 == s_p_19, s_OUT_reqWrite_19 == False, s_OUT_reqRead_19 == False, _smoother_0_avg_20 == (_smoother_0_avg_19 + s_OUT_value_19), s_p_20 == ((s_p_19 + 1) % 10)), And(And(And(Not(Or(False, m_IN_reqRead_19 == False)), m_IN_reqWrite_19), And(Not(Or(Or(Or(False, Not(s_OUT_reqRead_19 == And(s_OUT_reqWrite_19, _smoother_0_count_19 < 5))), Not(m_IN_reqWrite_19 == And(m_IN_reqRead_19, _smoother_0_count_19 == 5))), s_OUT_reqRead_19)), m_IN_reqWrite_19)), _smoother_0_count_20 == 0, m_IN_value_19 == (to_real(_smoother_0_avg_19) / to_real(5)), m_IN_reqWrite_19 == False, m_IN_reqRead_19 == False, s_p_20 == s_p_19, _smoother_0_avg_20 == _smoother_0_avg_19))
)

# Properties verification
# Property m_safe violation condition:
s.add(Or(
  Or(Not(m_IN_value_0 < 6), Not(m_IN_value_1 < 6), Not(m_IN_value_2 < 6), Not(m_IN_value_3 < 6), Not(m_IN_value_4 < 6), Not(m_IN_value_5 < 6), Not(m_IN_value_6 < 6), Not(m_IN_value_7 < 6), Not(m_IN_value_8 < 6), Not(m_IN_value_9 < 6), Not(m_IN_value_10 < 6), Not(m_IN_value_11 < 6), Not(m_IN_value_12 < 6), Not(m_IN_value_13 < 6), Not(m_IN_value_14 < 6), Not(m_IN_value_15 < 6), Not(m_IN_value_16 < 6), Not(m_IN_value_17 < 6), Not(m_IN_value_18 < 6), Not(m_IN_value_19 < 6), Not(m_IN_value_20 < 6))
))
print(s.check())
if s.check() == sat:
    m = s.model()
    print("counterexample model:")
    print(m)
